FROM alpine:latest

RUN apk update
RUN apk add python3
RUN apk add py3-pip
RUN pip install sockets 
RUN pip install numpy 

WORKDIR /home

COPY ./maphosts.py ./
COPY ./consumidor.py ./

CMD ["python3","consumidor.py"]
