FROM alpine:latest

RUN apk update
RUN apk add python3
RUN apk add py3-pip
RUN pip install sockets 
RUN pip install numpy 
RUN pip install pandas 

WORKDIR /home

COPY ./maphosts.py ./
COPY ./agenteSARSA.py ./

CMD ["python3","agenteSARSA.py"]
